const sheepToasts = [
    "Baa-lliant intelligence gathered.", "Clover density optimal in sector 7.", "Ewe are authorized for grazing.",
    "Wool market prices hit record highs.", "Tactical sweaters deployed.", "Wolf activity successfully neutralized.",
    "Weather Update: Mainz-Kastel stable.", "Status: 100% Mission Ready.", "Deploying the woolly vanguard.",
    "Fleece-force one is airborne.", "Shear perfection achieved in grid B.", "Rams are at peak performance.",
    "Ewe-nique signal detected in the south.", "Pasture perimeter secure.", "Grass height: Optimal for snacks.",
    "Alert: High-quality clover detected at coordinates 42.9, -71.2.", "Ewe are doing an amazing job, Commander.",
    "Wool you look at those stats!", "Don't be sheepish, deploy the fleet!", "Shear luck? No, pure skill.",
    "Mandalorian Intelligence: Sheep are honorable grazers.", "Clover Supply Chain: North pasture restocked.",
    "Internal Memo: Stop calling the Commander 'Baa-ss'.", "Training: Ramming speed practice scheduled.",
    "Status: 100% Baa-lliant operations confirmed.", "Lamb-orghini speeds detected in sector 4.",
    "Fleece Navidad! Deployment complete.", "Silence of the Lambs? No, total dominance.",
    "Counting sheep? Not today, we're on duty.", "Feeling ram-bunctious today, Commander?",
    "Ewe-phoria detected in the flock.", "Shear madness! Efficiency up by 20%.", "The grass is always greener on our side.",
    "Wool-power: The future of energy.", "Baa-ck to basics: More clover, more power.", "Sheep-shape and ready for action.",
    "Herd it through the grapevine: We're winning.", "Woolly mammoth DNA? No, just strong genes.",
    "Ewe-turn detected: Wolf retreating.", "Pasture patrol reporting for duty.", "Grass is the fuel of the future.",
    "Don't pull the wool over my eyes!", "Feeling like a total baa-dass today.", "Simply baa-rvelous performance.",
    "Flock-star status achieved.", "Ewe better believe it!", "The great escape? Not from this pasture.",
    "Fleece of mind: All sectors green.", "Shear willpower wins the day.", "Ram-page protocol: Disengaged.",
    "Ewe-topia is within reach.", "Wool-timate victory confirmed.", "Sheep-wrecked? No, ship-shape.",
    "Pasture prime time is now.", "Feeling fleece-y, might delete later.", "Baa-bara Ann reporting for duty.",
    "Ewe-gene reporting from the field.", "Wool-iam the conqueror leads the way.", "Shear-lock Holmes on the case.",
    "Ram-ses the great grazes here.", "Ewe-lysses S. Grant authorized for command.", "Fleece-a Minnelli singing our praises.",
    "Lamb-bert the lion-hearted sheep spotted.", "Wool-y Nelson on the radio.", "Shear-a-dactyls? No, just fast sheep.",
    "Ram-bo mode: Restricted access.", "Ewe-thanasia for bad vibes only.", "Fleece-ing the competition.",
    "Shear-ity begins at home pasture.", "Ram-ifications are looking positive.", "Ewe-logy for the fallen clover.",
    "Wool-f in sheep's clothing? Not on our watch.", "Baa-dminton tournament at 1400 hours.",
    "Ewe-kalaylee music detected in sector 9.", "Fleece-t of foot and mind.", "Shear determination pays off.",
    "Ram-bler on the loose.", "Ewe-nion of sheep demands more snacks.", "Wool-ly bully detected.",
    "Baa-nana snacks approved for the fleet.", "Ewe-phoric grazing session in progress.",
    "Fleece-t of the world, unite!", "Shear-iff in town: Sector 1 is secure.", "Ram-shackle fence repaired.",
    "Ewe-niversity of Grazing: Class is in session.", "Wool-f-proof gates operational.",
    "Baa-throom break over, back to duty.", "Ewe-nique opportunity for extra clover.",
    "Fleece-ing the sheep? No, just a trim.", "Shear-man tank? No, just a large ram.", "Ram-rod straight posture, soldier.",
    "Ewe-logizing the old fence.", "Wool-ly jumper deployed.", "Baa-llistic sheep detected.",
    "Ewe-niversal clover income approved.", "Fleece-t manager promoted to elite tier.",
    "Shear-ing is caring.", "Ram-parts fortified.", "Ewe-nify the flock!", "Wool-timate efficiency reached.",
    "Baa-baa black sheep? No, tactical green.", "Ewe-reka! New clover discovered.",
    "Fleece-t commander: Rank secured.", "Shear delight in the meadow.", "Ram-ble on, brave sheep."
];
