const shepherdWisdom = [
    "A happy sheep produces the finest tactical wool.",
    "The grass is always greener where you water it, but clover is the true fuel.",
    "A shepherd's dog is worth ten fences.",
    "Never underestimate a ram with a clear path.",
    "Soft wool comes from a hard day's grazing.",
    "Keep your eyes on the horizon and your feet in the pasture.",
    "The flock follows the one who knows the way to the sweetest grass.",
    "A wise shepherd knows every sheep by its 'Baa'.",
    "Shear today, sweaters tomorrow. Plan for the season.",
    "The wolf is a master of disguise, but the sheepdog never sleeps.",
    "Clover in the morning, a shepherd's warning. Clover at night, a sheep's delight.",
    "A flock in unity can weather any storm.",
    "Good wool is grown, not made. Patience is the shepherd's tool.",
    "Respect the ram, or feel the ram-ifications.",
    "The best shade for a sheep is the shadow of the shepherd.",
    "A dry sheep is a warm sheep. Seek the shelter.",
    "The shepherd's whistle is louder than the wolf's howl.",
    "Pasture rotation is the secret to a long life and sweet milk.",
    "Listen to the wind; the sheep already are.",
    "A full trough makes for a quiet night.",
    "Treat every lamb like it's the future of the flock.",
    "The shepherd who sleeps with the flock knows the heart of the pasture.",
    "Don't count your sheep before they're in the pen.",
    "A clean fleece is a badge of honor.",
    "The mountain is steep, but the sheep are strong.",
    "Silence in the pasture is often the loudest alarm.",
    "Every ewe has a story; a good shepherd listens.",
    "The bell-wether leads, but the shepherd directs.",
    "Trust your dog, but verify the gate.",
    "The finest merino comes from the coldest peaks.",
    "A shearer's hand must be as steady as his heart.",
    "Grazing is a marathon, not a sprint.",
    "The pasture is a classroom if you know how to observe.",
    "Wool-gathering is for dreamers; wool-growing is for doers.",
    "A sheep in the hand is worth two in the wolf's den.",
    "Keep your shears sharp and your spirit sharper.",
    "The flock is only as fast as its slowest member. Leave no one behind.",
    "Clarity of purpose leads to quality of wool.",
    "A shepherd's staff is for guidance, not for fear.",
    "The valley floor is easy, but the ridge has the best view.",
    "Even the smallest lamb can lead the way home.",
    "Pasture peace is won through sheepdog vigilance.",
    "A well-timed 'Baa' can change the mood of the whole flock.",
    "The seasons change, but the need for clover remains constant.",
    "High-altitude grazing builds character and thick coats.",
    "A shepherd without a dog is like a ship without a rudder.",
    "The path to the fold is never too long when the sun is setting.",
    "Merino is the armor of the gentle.",
    "A ram's horns are a crown he never takes off.",
    "The meadow's song is composed of a thousand nibbles.",
    "Keep the water clean and the spirit clearer.",
    "A good shepherd knows when to lead and when to follow.",
    "The fence is only a boundary for the body, not the mind.",
    "Sheep sense is better than common sense in a storm.",
    "Every sunrise is a new chance to find the perfect clover.",
    "Tactical wool is the result of strategic grazing.",
    "The shepherd's dog is the silent guardian of the night.",
    "Don't let the wolf pull the wool over your eyes.",
    "A flock's strength is measured by its youngest member.",
    "Grazing efficiency is the key to a legendary harvest.",
    "The mountain path is narrow, but the reward is vast.",
    "Trust the trail; the ancients trod it before you.",
    "A warm fleece is the best defense against a cold world.",
    "The shepherd's voice is the comfort of the hills.",
    "Clover density is the ultimate KPI.",
    "A ram in the brush is worth ten in the city.",
    "Never let the sun set on an open gate.",
    "The flock knows the shepherd's step from a mile away.",
    "Sheep-power is the cleanest energy in the pasture.",
    "A well-fed sheep is a quiet sheep.",
    "The shepherd's cloak is made of the history of his flock.",
    "Watch the lead ewe; she knows the shortcut.",
    "The first spring grass is the sweetest victory.",
    "Merino excellence requires mountain discipline.",
    "A dog's bark is the shepherd's radar.",
    "The pasture is a mirror of the shepherd's care.",
    "Shearing is a transformation, not an ending.",
    "The ram's charge is the pulse of the highlands.",
    "Keep the salt-lick full and the morale high.",
    "A sheep's loyalty is won with consistency and clover.",
    "The shepherd's wisdom is written in the tracks of the flock.",
    "Don't be sheepish about your achievements.",
    "The finest wool is grown in the quietest hours.",
    "A flock in flight is a sign of a failed perimeter.",
    "The shepherd's eye sees what the wolf hopes he misses.",
    "Clover is the currency of the meadow.",
    "A ram's pride is the strength of the lineage.",
    "The shepherd's heart is always in the pasture.",
    "Every Baa has a frequency; learn to tune in.",
    "High-yield wool is the result of low-stress environments.",
    "The mountain air is the breath of the flock.",
    "A shepherd's rest is earned in the heat of the day.",
    "Keep your flock close and your enemies at bay.",
    "The finest textures come from the harshest climates.",
    "A sheep's memory is longer than its tail.",
    "The shepherd's staff is a bridge, not a barrier.",
    "Clover is the secret ingredient in every masterwork.",
    "The flock's silence is the ultimate tactical advantage.",
    "A ram's spirit is the fire of the highlands.",
    "The shepherd's legacy is the health of the pasture.",
    "Every lamb is a promise of a better season."
];
